export const GAME_START = 'GAME_START';
export const GAME_CONNECT_TILE = 'GAME_CONNECT_TILE';
export const GAME_PLACE_STONE = 'GAME_PLACE_STONE';
export const GAME_REFILL_HAND = 'GAME_REFILL_HAND';
export const GAME_MERGE_STATE = 'GAME_MERGE_STATE';
